version: 2
jobs:
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - add_ssh_keys
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: src
      - run: |
          ssh-keyscan -H glassempty.com >> ~/.ssh/known_hosts
      - run: |
          sudo apt-get update && sudo apt-get install rsync
      - run: |
          rsync -va src max@glassempty.com:/home/max/
      - run: |
          ssh max@glassempty.com php /home/max/src/index.php
workflows:
  version: 2
  one_and_two:
    jobs:
      - two